services:
  - type: web
    name: fortx-caller-api
    runtime: python
    rootDir: caller-api
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_EcYUA7Zx6skv@ep-blue-bar-ak6i2l9p-pooler.c-3.us-west-2.aws.neon.tech/neondb?channel_binding=require&sslmode=require
      - key: JWT_SECRET
        generateValue: true
